# Generated by Django 3.0.8 on 2021-10-05 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_users', 'Can users')]},
        ),
    ]
